name: Auto Fix Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Replace with your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      # Step 4: Run black for code formatting
      - name: Format code with black
        run: black .

      # Step 5: Sort imports with isort
      - name: Sort imports with isort
        run: isort .

      # Step 6: Run flake8 for linting
      - name: Lint code with flake8
        run: flake8 .

      # Step 7: Commit and push changes (if any)
      - name: Commit and push changes
        if: success() && github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-fix: Code formatting and linting fixes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
